### ISSUE TITLE
RADAR Training Code

### ISSUE THREAD

**Issue by meng-wenlong** [IBM/RADAR#1]
Hi! I am very interested in your wonderful work. Could you open-source the RADAR training code, so that I can apply RADAR on other datasets and LLMs?

**Comment by GregxmHu** [comment]
Thanks for your interest in our work. 

I understand that releasing the training code will help your research, but currently, I cannot provide the training code since the code will have another commercial usage.

However, I can provide you with some references. For adversarial training, you can refer to TextGAIL :  [https://github.com/qywu/TextGAIL](https://github.com/qywu/TextGAIL) . We implemented our training framework based on this repository.

I also noticed that you just want to apply RADAR on some datasets. So how about using our trained checkpoints? We have released one RADAR-detector in huggingface: [https://huggingface.co/TrustSafeAI/RADAR-Vicuna-7B](https://huggingface.co/TrustSafeAI/RADAR-Vicuna-7B)
